# Generated by Django 2.1 on 2019-10-29 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^[7-9][0-9]{9}$')])),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Number of otp sent')),
                ('logged', models.BooleanField(default=False, help_text='If OTP Successful')),
                ('forgot', models.BooleanField(default=False, help_text='Only True for forgot password')),
                ('forgot_logged', models.BooleanField(default=False, help_text='Only True if validate otp for forgot password is successful ')),
            ],
        ),
    ]
